#-------------------------------
# Site Settings
title: Danto
description: Danto is a news and magazine Jekyll theme
logo: "/images/logo.svg" # You can add own logo. For example "/images/logo.svg".
logo_dark: "/images/logo-dark.svg"
color_scheme: auto # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.


#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: "首頁"
      url: "/"
    - title: "動態"
      url: "/latest/"
    - title: "Authors"
      url: "/authors/"
    - title: "視音"
      url: "/videos/"
    - title: "Pages"
      submenu:
      - url: "/about/"
        title: "張純如工作室"
      - url: "/elements/"
        title: "Elements"
      - url: "/contact/"
        title: "Contact"
      - url: "/featured/"
        title: "Featured"

# Call to action button
cta_button:
  enable: true
  


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero_title: 相信一個人的力量
  hero_description: 文字是保存靈魂精華的唯一方式。演講最令我激動之處在於，即使演講者已然作古，長眠地下，他們的精神依然永存。對我來說，這是真正的宗教——永生的最佳方式。


#-------------------------------
# Tags Section Settings
tags_section:
  enable: true
  number_posts: 3 # To control how many posts to show under each tag section, set the value to a number. Three is the default.
  number_columns: 3 # You can specify the number of columns from 1-4 for large screen resolution. By default, the theme uses three columns grid.
  tags:
    - tag: "專訪"
    - tag: "張盈盈專欄"
    - tag: "熱點"
    - tag: "紀念"
    - tag: "超级純如"

# You can add many tag sections to the homepage; each section will show the recent posts by the tag.


#-------------------------------
# Authors Section Settings
authors_section:
  enable: true
  section_title: Meet our authors


#-------------------------------
# Footer Settings
footer_description: 人其實是死兩次：一次是肉體的死亡，一次是在他人的記憶中消失


# Social Links
social:
- {icon: "twitter", link: "https://twitter.com"}
- {icon: "facebook", link: "https://facebook.com"}
- {icon: "codepen", link: "https://codepen.io"}
- {icon: "pinterest", link: "https://pinterest.com"}
- {icon: "github", link: "https://github.com"}
- {icon: "youtube", link: "https://youtube.com"}

# Example of adding a new link to the footer - {icon: "instagram", link: "https://instagram.com"}
# Other icons can be found at https://ionicons.com/v4/


#-------------------------------
# Newsletter Settings
mailchimp_settings:
  enable: true
  mailchimp_title: 
  mailchimp_description: 從我的作家生涯中我領悟到，聽從自己的心聲和內在激情，努力創造擁有永久價值的東西，這才是通向成功的不二法門。很多時候，這意味著獨闢蹊徑。
 


#-------------------------------
# Contact Settings
contact:
  email: your@email.com # Add your form_id
  description: Danto comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form

# NOTE
# Danto theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus_identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test


#-------------------------------
# Google Analytics
google_analytics: # Add your GA Tracking Id
